language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: python test_app.py
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: wPXzM0hEtIXO09YTWusmio/01ivZG9p/mmZf1QD/R1nQqZIXMh8YFJq8wmJBHxrXbBnwLUbUO9pXJjdSN4xY5qklO6l/UXDta1Rq9zEVqxyyPSMAL0kH21AqrFGPVdfIKnISpdmQ0rpPHUAwB6YzfM8fLUedM6PPrsz39czXY4JDMELN82UTd83XzP0QxZtSk7KHd/lwG0UFJLfXZ9koMA2urpgCpED+z518mlm/jnrvarXMgekg8+e2BAet8bKjtrU8HKLLWkcuDTNe14EQcsRqEAIdCyXWTvoRHWQreZB/Vw676pBMozlISW/fv7QInn0r7uEDawXY2EoS2jJU1Q22exIeledAZTHAdXMDoIDfvQtLzyWCorH68Zw4forvrfrZ0haGhdNsHX6t7GHxOJiidEG6f/NbpSJatthD4NR8F+sLyxEEQHFAS976uUEmp/QNVdoWE/ponUQqp27JAbxKYecfM09UsEElakTssEDV3A9RfRTbq3VFkSrdxTap6d8EJxVA606AbZ8FGyqxI25du4pBQZ3CfZl6pOmvfoFRH/tzZhER8HuWy7004qW6Ve00iUjxMAY2sCdtImA5EJcNxb9CbBIabvOXFbTUdf44KpadInyuIMVT2934Ou2iiNV7aDr4/shAdl/J9x3RklvlIEW0pBTrSktT7CEP2VM=
